name: Pull Request Check

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  build:
    name: Build nodejs
    uses: ./.github/workflows/build.yml
    with:
      runs-on: "ubuntu-latest"
  plan:
    name: Terraform plan
    needs: [build]
    uses: ./.github/workflows/terraform-plan.yml
    with:
      config_directory: "/terraform"
    secrets: inherit
