name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build node
    uses: ./.github/workflows/build.yml
    with:
      runs-on: "ubuntu-latest"
  terraform-plan:
    name: Terraform plan
    needs: [build]
    uses: ./.github/workflows/terraform-plan.yml
    with:
      config_directory: "/terraform"
  terraform-apply:
    name: Terraform apply
    needs: [terraform-plan]
    uses: ./.github/workflows/terraform-apply.yml 
