name: Release Workflow
env:
  CONFIG_DIRECTORY: "./terraform"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build node
    uses: ./.github/workflows/build.yml
    with:
      runs-on: "ubuntu-latest"
  terraform-plan:
    name: Terraform plan
    uses: ./.github/workflows/terraform-plan.yml
  terraform-apply:
    name: Terraform apply
    uses: ./.github/workflows/terraform-apply.yml 
