name: Release Workflow
env:
  CONFIG_DIRECTORY: "./terraform"
  repository: ${{github.repository}}

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ${{env.repository}}/.github/workflows/build.yml
      with:
        runs-on: "ubuntu-latest"
    
    - uses: ${{env.repository}}/.github/workflows/terraform-plan.yml
    - uses: ${{env.repository}}/.github/workflows/terraform-apply.yml

  
