name: Release Workflow
env:
  CONFIG_DIRECTORY: "./terraform"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/workflows/build.yml@main
      with:
        runs-on: "ubuntu-latest"
    
    - uses: ./.github/workflows/terraform-plan.yml@main
    - uses: ./.github/workflows/terraform-apply.yml@main

  
