name: Release Dev Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
    check:
      uses: asbaba-corp/pipelines/.github/workflows/release-dev.yml@main
      with:
        repository_language: "nodejs"
      secrets: inherit   
