name: Release Dev Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    check:
      uses: asbaba-corp/pipelines/.github/workflows/release-dev.yml@main
      with:
        repository_language: "nodejs"
      secrets: inherit   
      
