name: "Terraform Apply"

on: workflow_dispatch 
env:
  TF_CLOUD_ORGANIZATION: "Cataprato"
  TF_WORKSPACE: "cataprato-workspace"
  CONFIG_DIRECTORY: "./terraform"
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  

jobs:
  build:
    uses: ./.github/workflows/build.yml
  
    
  zip:
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Check files
        run: ls
        
      - name: Zip Files
        run: zip -qq -r dist.zip . 
 
  plan:
    uses: ./.github/workflows/terraform-plan.yml
    needs: [zip]
    secrets: inherit

    
  Terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [plan]
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    steps:
    
      - uses: actions/checkout@v3
      - name: check files
        run: ls
        
      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
