name: PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    uses: filipezz/pokedex/.github/workflows/build.yml@main
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: dist
          
      - name: Checking files  
        run: ls

     
      
