name: PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: dist-${{ github.sha }}
          
      - name: Checking files  
        run: ls

     
      
